#!/usr//bin/python3
def raise_exception():
    raise Exception("Error has been raised!")
